### ISSUE TITLE
Can't  render the Table Of Contents correctly 

### ISSUE THREAD

**Issue by wybaby168** [VolodymyrBaydalka/docxjs#29] opened 2022-01-27 03:13 UTC
Please support the Table Of Contents with click and redirect, which like the anchor. Thank you very much! The catalog of the rendered html can't work now.

**Comment by zVolodymyr** [comment] 2022-02-24 09:24
Hi. What is catalog? Could you provide example file and example of desired result?

**Comment by wybaby168** [comment] 2022-05-26 01:18
Sorry, maybe I didn't express clearly.  The "catalog" I mentioned refers to the table of contents inserted into the word document. Which was inserted through the references tab. Generally, we can click on an item in the table of contents to quickly jump to the corresponding anchor point. Thanks for your reply!😊

**Comment by VolodymyrBaydalka** [comment] 2023-12-28 20:20
Duplicate of #4

**Closed by VolodymyrBaydalka** 2023-12-28 20:20 UTC
