### ISSUE TITLE
[BUG] - Multi page docx is rendered as single page html

### ISSUE THREAD

**Issue by sujit-baniya** [VolodymyrBaydalka/docxjs#89] opened 2023-11-27 09:49 UTC
**Describe the bug**
The docx file with no page break (continuous multiple pages) is rendered as single page html in preview

**Document**
If applicable, add *.docx document to help explain your problem.

**Expected behavior**
Page break is expected with header and footer as in the document

**Additional context**
[Sample.zip](https://github.com/VolodymyrBaydalka/docxjs/files/13472496/Sample.zip)

**Comment by VolodymyrBaydalka** [comment] 2023-12-21 23:59
Duplicate of #39

**Closed by VolodymyrBaydalka** 2023-12-21 23:59 UTC
